# # docker-compose.yml
# # The - "3000:3000" syntax in the Docker Compose file is used to 
# # map ports between the container and the host machine.
# # The format is - "<host-port>:<container-port>".
version: "3.4"

services:
  nodejs:
    container_name: nodejs
    ports:
      - 3080:3080               # Change it to 9000:3080 to use nginx
    depends_on:
      - mongodb
    build:
      context: ./newbackend
      dockerfile: Dockerfile
    image: ethan929/nodejs:100
    restart: always
    env_file:
      - ./newbackend/.env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/chatgpt-clone
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_HTTP_ADDR=meilisearch:7700
    volumes:
      - /client/node_modules
      - ./newbackend:/newbackend
      - /newbackend/node_modules
  mongodb:
    container_name: mongodb
    ports:
      - 27018:27017
    image: mongo
    restart: always
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth # this is for dev, no auth
  # meilisearch:
  #   container_name: chat-meilisearch
  #   image: getmeili/meilisearch:v1.0
  #   ports:
  #     - 7700:7700
  #   env_file:
  #     - ./newbackend/.env
  #   environment:
  #     - MEILI_HOST=http://meilisearch:7700
  #     - MEILI_HTTP_ADDR=meilisearch:7700
  #   volumes:
  #     - ./meili_data:/meili_data
